import streamlit as st
from langchain_experimental.agents import create_csv_agent
from langchain.llms import OpenAI
from dotenv import load_dotenv
from vector import process_csv_to_chroma


def main():

    # access to env variables
    load_dotenv()

    #streamlit front-end setup
    st.set_page_config(page_title="Ask you CSV 📈")
    st.header("Ask you CSV 📈")

    user_csv = st.file_uploader("Upload your CSV file", type="csv")

    # test if csv is loaded
    if user_csv is not None :
        user_question = st.text_input("Ask a question about your CSV:")
        #upload csv to vectordb
        process_csv_to_chroma(user_csv)

        llm = OpenAI(temperature=0)
        #initializing our agent
        agent = create_csv_agent(llm, user_csv, verbose=True, allow_dangerous_code=True)

        if user_question is not None and user_question != "" :
           # response generated by our agent after it being passed the user question
            response = agent.run(user_question)
            st.write(response)

if __name__ == "__main__":
    main()